### ISSUE TITLE
typo on website

### ISSUE THREAD

**Issue by keesj** [mjoldfield/ice40-blinky#1]
Hi,

there is a typo on the following page. 
https://mjoldfield.com/atelier/2018/02/ice40-blinky-icestick.html

![selection_161 png](https://user-images.githubusercontent.com/57112/51497731-521df000-1dc4-11e9-8114-33d88bcd9979.png)
The pin used is not 12 but 21

Thanks for creating the repository and website

**Comment by mjoldfield** [comment]
Thanks, I've fixed this now.
